### PR TITLE
Prevent marks from being cleared in addition to measures.

### PR DESCRIPTION
**Pull request by runspired**

### CODE REVIEW

**Comment by sangm** [comment]
What about `Performance.clearResourceTimings()`?

**Comment by runspired** [comment]
@sangm not familiar with that one but that also wont cause a bug if in use unlike these other things.

**Comment by scalvert** [comment]
This appears to be causing issues within tests. I see some tests failing due to `mark_boot_start` not being present.

Do we have an ETA for this to be fixed?

**Comment by stefanpenner** [comment]
> Do we have an ETA for this to be fixed?

What is `this`? Does the PR itself address the issue, or are do we need to do more?

**Comment by runspired** [comment]
@stefanpenner PR addresses the issue

**Comment by stefanpenner** [comment]
released as v1.2.1 🎉

**Pull request merged**
